[package]
name = "iso-bmff"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"

[lib]

[dependencies]
iso-bmff-macros = { version = "0.1", path = "iso-bmff-macros" }
