[package]
name = "macrotest"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.11", features = [ "full" ] }
